#!/usr/bin/env bash
# G1 iOS CI - NON-PRODUCTION / SYNTHETIC DATA ONLY.
# Regenerates the synthetic dataset on this host with the pinned generator, checks every output against the committed
# GENERATION_RECORD.json (cross-platform determinism), runs the independent verifier, then places the binary outputs into
# synthetic-data/out. Fails on any difference.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
: "${EVIDENCE_DIR:=$root/evidence}"
: "${WORK_DIR:=${RUNNER_TEMP:-/tmp}}"
mkdir -p "$EVIDENCE_DIR"
cd "$root/synthetic-data"
test "$(node --version)" = "v24.13.1"
npm ci --ignore-scripts --no-audit --no-fund > "$EVIDENCE_DIR/data-npm-ci.txt" 2>&1
node fetch-inputs.mjs "$WORK_DIR/g1-fonts" > "$EVIDENCE_DIR/data-fetch-inputs.txt" 2>&1
rm -rf "$WORK_DIR/g1-out"
node generate.mjs --out "$WORK_DIR/g1-out" --fonts "$WORK_DIR/g1-fonts" --w-start 2026-10-01T00:00:00Z > "$EVIDENCE_DIR/data-generate.txt" 2>&1
# independent verifier in a private virtual environment (the runner's Python is externally managed, PEP 668)
python3 -m venv "$WORK_DIR/g1-venv"
"$WORK_DIR/g1-venv/bin/python" -m pip install --quiet --disable-pip-version-check cryptography==46.0.7 > "$EVIDENCE_DIR/data-pip.txt" 2>&1
"$WORK_DIR/g1-venv/bin/python" check/verify.py "$WORK_DIR/g1-out" > "$EVIDENCE_DIR/data-verify.json"
python3 - "$WORK_DIR/g1-out" out "$EVIDENCE_DIR/data-regeneration.json" <<'PY'
import hashlib, json, pathlib, shutil, sys
new, committed, report = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
a = json.loads((committed / "GENERATION_RECORD.json").read_text(encoding="utf-8"))
b = json.loads((new / "GENERATION_RECORD.json").read_text(encoding="utf-8"))
oa = {o["path"]: o["sha256"] for o in a["outputs"]}
ob = {o["path"]: o["sha256"] for o in b["outputs"]}
diff = sorted(p for p in set(oa) | set(ob) if oa.get(p) != ob.get(p))
same = not diff and a["bundle"] == b["bundle"] and a["oracle_sha256"] == b["oracle_sha256"] and a["generator"]["source"] == b["generator"]["source"]
result = {"committed_runtime": a["runtime"], "regenerated_runtime": b["runtime"], "committed_tools": a["tools"], "regenerated_tools": b["tools"],
          "outputs": len(ob), "differences": diff, "bundle_sha256": b["bundle"]["bundle_sha256"], "zip_sha256": b["bundle"]["zip_sha256"],
          "oracle_sha256": b["oracle_sha256"], "byte_identical": same}
report.write_text(json.dumps(result, indent=1) + "\n", encoding="utf-8")
if not same:
    sys.exit("regenerated dataset differs from the committed record: %s" % diff[:10])
for p in ob:
    target = committed / p
    data = (new / p).read_bytes()
    assert hashlib.sha256(data).hexdigest() == oa[p]
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
print("dataset regenerated byte-identically:", len(ob), "outputs")
PY
"$root/ios-ci/prepare-assets.sh"
